
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/html

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
      runas: root
