version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 154020000542.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - docker build -t your-image-name .
      - docker tag your-image-name:latest your-ecr-repo-uri:latest
  post_build:
    commands:
      - docker push your-ecr-repo-uri:latest
