version: 0.2

phases:
  pre_build:
    commands:
     
  build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 154020000542.dkr.ecr.ap-south-1.amazonaws.com
      - sudo docker build -t react-app .
      - sudo docker tag react-app:latest 154020000542.dkr.ecr.ap-south-1.amazonaws.com/react-app:latest
      - sudo docker push 154020000542.dkr.ecr.ap-south-1.amazonaws.com/react-app:latest
  post_build:
    commands:
      
