version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1
  build:
    commands:
      - build -t reactapp:1.0 .
      - docker tag reactapp:1.0 154020000542.dkr.ecr.ap-south-1.amazonaws.com/react-app:latest
  post_build:
    commands:
      - docker push 154020000542.dkr.ecr.ap-south-1.amazonaws.com/react-app:latest
